"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-python
from fuse-python.model.country_code import CountryCode
from fuse-python.model.financial_institution_logo import FinancialInstitutionLogo
globals()['CountryCode'] = CountryCode
globals()['FinancialInstitutionLogo'] = FinancialInstitutionLogo
from fuse-python.model.financial_institution import FinancialInstitution


class TestFinancialInstitution(unittest.TestCase):
    """FinancialInstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialInstitution(self):
        """Test FinancialInstitution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FinancialInstitution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
