"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-python
from fuse-python.model.financial_connection_data import FinancialConnectionData
from fuse-python.model.financial_connections_account import FinancialConnectionsAccount
globals()['FinancialConnectionData'] = FinancialConnectionData
globals()['FinancialConnectionsAccount'] = FinancialConnectionsAccount
from fuse-python.model.get_financial_connections_accounts_response import GetFinancialConnectionsAccountsResponse


class TestGetFinancialConnectionsAccountsResponse(unittest.TestCase):
    """GetFinancialConnectionsAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFinancialConnectionsAccountsResponse(self):
        """Test GetFinancialConnectionsAccountsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetFinancialConnectionsAccountsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
