"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-python
from fuse-python.model.aggregator import Aggregator
globals()['Aggregator'] = Aggregator
from fuse-python.model.create_entity_response import CreateEntityResponse


class TestCreateEntityResponse(unittest.TestCase):
    """CreateEntityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEntityResponse(self):
        """Test CreateEntityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateEntityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
