"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-python
from fuse-python.model.account_subtype import AccountSubtype
from fuse-python.model.account_type import AccountType
from fuse-python.model.financial_connections_account_cached_balance import FinancialConnectionsAccountCachedBalance
from fuse-python.model.financial_connections_account_institution import FinancialConnectionsAccountInstitution
globals()['AccountSubtype'] = AccountSubtype
globals()['AccountType'] = AccountType
globals()['FinancialConnectionsAccountCachedBalance'] = FinancialConnectionsAccountCachedBalance
globals()['FinancialConnectionsAccountInstitution'] = FinancialConnectionsAccountInstitution
from fuse-python.model.financial_connections_account import FinancialConnectionsAccount


class TestFinancialConnectionsAccount(unittest.TestCase):
    """FinancialConnectionsAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinancialConnectionsAccount(self):
        """Test FinancialConnectionsAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FinancialConnectionsAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
