"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fuse-python
from fuse-python.model.financial_connections_account import FinancialConnectionsAccount
from fuse-python.model.financial_connections_holding import FinancialConnectionsHolding
globals()['FinancialConnectionsAccount'] = FinancialConnectionsAccount
globals()['FinancialConnectionsHolding'] = FinancialConnectionsHolding
from fuse-python.model.get_investment_holdings_response import GetInvestmentHoldingsResponse


class TestGetInvestmentHoldingsResponse(unittest.TestCase):
    """GetInvestmentHoldingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInvestmentHoldingsResponse(self):
        """Test GetInvestmentHoldingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInvestmentHoldingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
