# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import fuse_py
from fuse_py.model.get_financial_connections_account_details_response import GetFinancialConnectionsAccountDetailsResponse
from fuse_py import configuration


class TestGetFinancialConnectionsAccountDetailsResponse(unittest.TestCase):
    """GetFinancialConnectionsAccountDetailsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
