# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import fuse_client
from fuse_client.model.add_spend_power_transaction_response import AddSpendPowerTransactionResponse
from fuse_client import configuration


class TestAddSpendPowerTransactionResponse(unittest.TestCase):
    """AddSpendPowerTransactionResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
