# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import fuse_py
from fuse_py.model.sync_financial_connections_data_response import SyncFinancialConnectionsDataResponse
from fuse_py import configuration


class TestSyncFinancialConnectionsDataResponse(unittest.TestCase):
    """SyncFinancialConnectionsDataResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
