# flake8: noqa

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.1"

# import ApiClient
from fuse-python.api_client import ApiClient

# import Configuration
from fuse-python.configuration import Configuration

# import exceptions
from fuse-python.exceptions import OpenApiException
from fuse-python.exceptions import ApiAttributeError
from fuse-python.exceptions import ApiTypeError
from fuse-python.exceptions import ApiValueError
from fuse-python.exceptions import ApiKeyError
from fuse-python.exceptions import ApiException
