# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fuse_client import schemas  # noqa: F401


class TransactionCategoryPrimary(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Primary transaction category
    """


    class MetaOapg:
        enum_value_to_name = {
            "income": "INCOME",
            "transfer_in": "TRANSFER_IN",
            "transfer_out": "TRANSFER_OUT",
            "loan_payments": "LOAN_PAYMENTS",
            "bank_fees": "BANK_FEES",
            "entertainment": "ENTERTAINMENT",
            "food_and_drink": "FOOD_AND_DRINK",
            "general_merchandise": "GENERAL_MERCHANDISE",
            "home_improvement": "HOME_IMPROVEMENT",
            "medical": "MEDICAL",
            "personal_care": "PERSONAL_CARE",
            "general_services": "GENERAL_SERVICES",
            "government_and_non_profit": "GOVERNMENT_AND_NON_PROFIT",
            "transportation": "TRANSPORTATION",
            "travel": "TRAVEL",
            "rent_and_utilities": "RENT_AND_UTILITIES",
        }
    
    @schemas.classproperty
    def INCOME(cls):
        return cls("income")
    
    @schemas.classproperty
    def TRANSFER_IN(cls):
        return cls("transfer_in")
    
    @schemas.classproperty
    def TRANSFER_OUT(cls):
        return cls("transfer_out")
    
    @schemas.classproperty
    def LOAN_PAYMENTS(cls):
        return cls("loan_payments")
    
    @schemas.classproperty
    def BANK_FEES(cls):
        return cls("bank_fees")
    
    @schemas.classproperty
    def ENTERTAINMENT(cls):
        return cls("entertainment")
    
    @schemas.classproperty
    def FOOD_AND_DRINK(cls):
        return cls("food_and_drink")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE(cls):
        return cls("general_merchandise")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT(cls):
        return cls("home_improvement")
    
    @schemas.classproperty
    def MEDICAL(cls):
        return cls("medical")
    
    @schemas.classproperty
    def PERSONAL_CARE(cls):
        return cls("personal_care")
    
    @schemas.classproperty
    def GENERAL_SERVICES(cls):
        return cls("general_services")
    
    @schemas.classproperty
    def GOVERNMENT_AND_NON_PROFIT(cls):
        return cls("government_and_non_profit")
    
    @schemas.classproperty
    def TRANSPORTATION(cls):
        return cls("transportation")
    
    @schemas.classproperty
    def TRAVEL(cls):
        return cls("travel")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES(cls):
        return cls("rent_and_utilities")
