# coding: utf-8

"""
    Fuse

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from fuse_client import schemas  # noqa: F401


class TransactionCategoryDetailed(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Detailed transaction category
    """


    class MetaOapg:
        enum_value_to_name = {
            "income_dividends": "INCOME_DIVIDENDS",
            "income_interest_earned": "INCOME_INTEREST_EARNED",
            "income_retirement_pension": "INCOME_RETIREMENT_PENSION",
            "income_tax_refund": "INCOME_TAX_REFUND",
            "income_unemployment": "INCOME_UNEMPLOYMENT",
            "income_wages": "INCOME_WAGES",
            "income_other_income": "INCOME_OTHER_INCOME",
            "transfer_in_cash_advances_and_loans": "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
            "transfer_in_deposit": "TRANSFER_IN_DEPOSIT",
            "transfer_in_investment_and_retirement_funds": "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
            "transfer_in_savings": "TRANSFER_IN_SAVINGS",
            "transfer_in_account_transfer": "TRANSFER_IN_ACCOUNT_TRANSFER",
            "transfer_in_other_transfer_in": "TRANSFER_IN_OTHER_TRANSFER_IN",
            "transfer_out_investment_and_retirement_funds": "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
            "transfer_out_savings": "TRANSFER_OUT_SAVINGS",
            "transfer_out_withdrawal": "TRANSFER_OUT_WITHDRAWAL",
            "transfer_out_account_transfer": "TRANSFER_OUT_ACCOUNT_TRANSFER",
            "transfer_out_other_transfer_out": "TRANSFER_OUT_OTHER_TRANSFER_OUT",
            "loan_payments_car_payment": "LOAN_PAYMENTS_CAR_PAYMENT",
            "loan_payments_credit_card_payment": "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
            "loan_payments_personal_loan_payment": "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
            "loan_payments_mortgage_payment": "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
            "loan_payments_student_loan_payment": "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
            "loan_payments_other_payment": "LOAN_PAYMENTS_OTHER_PAYMENT",
            "bank_fees_atm_fees": "BANK_FEES_ATM_FEES",
            "bank_fees_foreign_transaction_fees": "BANK_FEES_FOREIGN_TRANSACTION_FEES",
            "bank_fees_insufficient_funds": "BANK_FEES_INSUFFICIENT_FUNDS",
            "bank_fees_interest_charge": "BANK_FEES_INTEREST_CHARGE",
            "bank_fees_overdraft_fees": "BANK_FEES_OVERDRAFT_FEES",
            "bank_fees_other_bank_fees": "BANK_FEES_OTHER_BANK_FEES",
            "entertainment_casinos_and_gambling": "ENTERTAINMENT_CASINOS_AND_GAMBLING",
            "entertainment_music_and_audio": "ENTERTAINMENT_MUSIC_AND_AUDIO",
            "entertainment_sporting_events_amusement_parks_and_museums": "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
            "entertainment_tv_and_movies": "ENTERTAINMENT_TV_AND_MOVIES",
            "entertainment_video_games": "ENTERTAINMENT_VIDEO_GAMES",
            "entertainment_other_entertainment": "ENTERTAINMENT_OTHER_ENTERTAINMENT",
            "food_and_drink_beer_wine_and_liquor": "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR",
            "food_and_drink_coffee": "FOOD_AND_DRINK_COFFEE",
            "food_and_drink_fast_food": "FOOD_AND_DRINK_FAST_FOOD",
            "food_and_drink_groceries": "FOOD_AND_DRINK_GROCERIES",
            "food_and_drink_restaurant": "FOOD_AND_DRINK_RESTAURANT",
            "food_and_drink_vending_machines": "FOOD_AND_DRINK_VENDING_MACHINES",
            "food_and_drink_other_food_and_drink": "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK",
            "general_merchandise_bookstores_and_newsstands": "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS",
            "general_merchandise_clothing_and_accessories": "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES",
            "general_merchandise_convenience_stores": "GENERAL_MERCHANDISE_CONVENIENCE_STORES",
            "general_merchandise_department_stores": "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
            "general_merchandise_discount_stores": "GENERAL_MERCHANDISE_DISCOUNT_STORES",
            "general_merchandise_electronics": "GENERAL_MERCHANDISE_ELECTRONICS",
            "general_merchandise_gifts_and_novelties": "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES",
            "general_merchandise_office_supplies": "GENERAL_MERCHANDISE_OFFICE_SUPPLIES",
            "general_merchandise_online_marketplaces": "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
            "general_merchandise_pet_supplies": "GENERAL_MERCHANDISE_PET_SUPPLIES",
            "general_merchandise_sporting_goods": "GENERAL_MERCHANDISE_SPORTING_GOODS",
            "general_merchandise_superstores": "GENERAL_MERCHANDISE_SUPERSTORES",
            "general_merchandise_tobacco_and_vape": "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE",
            "general_merchandise_other_general_merchandise": "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
            "home_improvement_furniture": "HOME_IMPROVEMENT_FURNITURE",
            "home_improvement_hardware": "HOME_IMPROVEMENT_HARDWARE",
            "home_improvement_repair_and_maintenance": "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE",
            "home_improvement_security": "HOME_IMPROVEMENT_SECURITY",
            "home_improvement_other_home_improvement": "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT",
            "medical_dental_care": "MEDICAL_DENTAL_CARE",
            "medical_eye_care": "MEDICAL_EYE_CARE",
            "medical_nursing_care": "MEDICAL_NURSING_CARE",
            "medical_pharmacies_and_supplements": "MEDICAL_PHARMACIES_AND_SUPPLEMENTS",
            "medical_primary_care": "MEDICAL_PRIMARY_CARE",
            "medical_veterinary_services": "MEDICAL_VETERINARY_SERVICES",
            "medical_other_medical": "MEDICAL_OTHER_MEDICAL",
            "personal_care_gyms_and_fitness_centers": "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
            "personal_care_hair_and_beauty": "PERSONAL_CARE_HAIR_AND_BEAUTY",
            "personal_care_laundry_and_dry_cleaning": "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING",
            "personal_care_other_personal_care": "PERSONAL_CARE_OTHER_PERSONAL_CARE",
            "general_services_accounting_and_financial_planning": "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
            "general_services_automotive": "GENERAL_SERVICES_AUTOMOTIVE",
            "general_services_childcare": "GENERAL_SERVICES_CHILDCARE",
            "general_services_consulting_and_legal": "GENERAL_SERVICES_CONSULTING_AND_LEGAL",
            "general_services_education": "GENERAL_SERVICES_EDUCATION",
            "general_services_insurance": "GENERAL_SERVICES_INSURANCE",
            "general_services_postage_and_shipping": "GENERAL_SERVICES_POSTAGE_AND_SHIPPING",
            "general_services_storage": "GENERAL_SERVICES_STORAGE",
            "general_services_other_general_services": "GENERAL_SERVICES_OTHER_GENERAL_SERVICES",
            "government_and_non_profit_donations": "GOVERNMENT_AND_NON_PROFIT_DONATIONS",
            "government_and_non_profit_government_departments_and_agencies": "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES",
            "government_and_non_profit_tax_payment": "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
            "government_and_non_profit_other_government_and_non_profit": "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT",
            "transportation_bikes_and_scooters": "TRANSPORTATION_BIKES_AND_SCOOTERS",
            "transportation_gas": "TRANSPORTATION_GAS",
            "transportation_parking": "TRANSPORTATION_PARKING",
            "transportation_public_transit": "TRANSPORTATION_PUBLIC_TRANSIT",
            "transportation_taxis_and_ride_shares": "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
            "transportation_tolls": "TRANSPORTATION_TOLLS",
            "transportation_other_transportation": "TRANSPORTATION_OTHER_TRANSPORTATION",
            "travel_flights": "TRAVEL_FLIGHTS",
            "travel_lodging": "TRAVEL_LODGING",
            "travel_rental_cars": "TRAVEL_RENTAL_CARS",
            "travel_other_travel": "TRAVEL_OTHER_TRAVEL",
            "rent_and_utilities_gas_and_electricity": "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
            "rent_and_utilities_internet_and_cable": "RENT_AND_UTILITIES_INTERNET_AND_CABLE",
            "rent_and_utilities_rent": "RENT_AND_UTILITIES_RENT",
            "rent_and_utilities_sewage_and_waste_management": "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT",
            "rent_and_utilities_telephone": "RENT_AND_UTILITIES_TELEPHONE",
            "rent_and_utilities_water": "RENT_AND_UTILITIES_WATER",
            "rent_and_utilities_other_utilities": "RENT_AND_UTILITIES_OTHER_UTILITIES",
        }
    
    @schemas.classproperty
    def INCOME_DIVIDENDS(cls):
        return cls("income_dividends")
    
    @schemas.classproperty
    def INCOME_INTEREST_EARNED(cls):
        return cls("income_interest_earned")
    
    @schemas.classproperty
    def INCOME_RETIREMENT_PENSION(cls):
        return cls("income_retirement_pension")
    
    @schemas.classproperty
    def INCOME_TAX_REFUND(cls):
        return cls("income_tax_refund")
    
    @schemas.classproperty
    def INCOME_UNEMPLOYMENT(cls):
        return cls("income_unemployment")
    
    @schemas.classproperty
    def INCOME_WAGES(cls):
        return cls("income_wages")
    
    @schemas.classproperty
    def INCOME_OTHER_INCOME(cls):
        return cls("income_other_income")
    
    @schemas.classproperty
    def TRANSFER_IN_CASH_ADVANCES_AND_LOANS(cls):
        return cls("transfer_in_cash_advances_and_loans")
    
    @schemas.classproperty
    def TRANSFER_IN_DEPOSIT(cls):
        return cls("transfer_in_deposit")
    
    @schemas.classproperty
    def TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS(cls):
        return cls("transfer_in_investment_and_retirement_funds")
    
    @schemas.classproperty
    def TRANSFER_IN_SAVINGS(cls):
        return cls("transfer_in_savings")
    
    @schemas.classproperty
    def TRANSFER_IN_ACCOUNT_TRANSFER(cls):
        return cls("transfer_in_account_transfer")
    
    @schemas.classproperty
    def TRANSFER_IN_OTHER_TRANSFER_IN(cls):
        return cls("transfer_in_other_transfer_in")
    
    @schemas.classproperty
    def TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS(cls):
        return cls("transfer_out_investment_and_retirement_funds")
    
    @schemas.classproperty
    def TRANSFER_OUT_SAVINGS(cls):
        return cls("transfer_out_savings")
    
    @schemas.classproperty
    def TRANSFER_OUT_WITHDRAWAL(cls):
        return cls("transfer_out_withdrawal")
    
    @schemas.classproperty
    def TRANSFER_OUT_ACCOUNT_TRANSFER(cls):
        return cls("transfer_out_account_transfer")
    
    @schemas.classproperty
    def TRANSFER_OUT_OTHER_TRANSFER_OUT(cls):
        return cls("transfer_out_other_transfer_out")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_CAR_PAYMENT(cls):
        return cls("loan_payments_car_payment")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_CREDIT_CARD_PAYMENT(cls):
        return cls("loan_payments_credit_card_payment")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT(cls):
        return cls("loan_payments_personal_loan_payment")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_MORTGAGE_PAYMENT(cls):
        return cls("loan_payments_mortgage_payment")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT(cls):
        return cls("loan_payments_student_loan_payment")
    
    @schemas.classproperty
    def LOAN_PAYMENTS_OTHER_PAYMENT(cls):
        return cls("loan_payments_other_payment")
    
    @schemas.classproperty
    def BANK_FEES_ATM_FEES(cls):
        return cls("bank_fees_atm_fees")
    
    @schemas.classproperty
    def BANK_FEES_FOREIGN_TRANSACTION_FEES(cls):
        return cls("bank_fees_foreign_transaction_fees")
    
    @schemas.classproperty
    def BANK_FEES_INSUFFICIENT_FUNDS(cls):
        return cls("bank_fees_insufficient_funds")
    
    @schemas.classproperty
    def BANK_FEES_INTEREST_CHARGE(cls):
        return cls("bank_fees_interest_charge")
    
    @schemas.classproperty
    def BANK_FEES_OVERDRAFT_FEES(cls):
        return cls("bank_fees_overdraft_fees")
    
    @schemas.classproperty
    def BANK_FEES_OTHER_BANK_FEES(cls):
        return cls("bank_fees_other_bank_fees")
    
    @schemas.classproperty
    def ENTERTAINMENT_CASINOS_AND_GAMBLING(cls):
        return cls("entertainment_casinos_and_gambling")
    
    @schemas.classproperty
    def ENTERTAINMENT_MUSIC_AND_AUDIO(cls):
        return cls("entertainment_music_and_audio")
    
    @schemas.classproperty
    def ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS(cls):
        return cls("entertainment_sporting_events_amusement_parks_and_museums")
    
    @schemas.classproperty
    def ENTERTAINMENT_TV_AND_MOVIES(cls):
        return cls("entertainment_tv_and_movies")
    
    @schemas.classproperty
    def ENTERTAINMENT_VIDEO_GAMES(cls):
        return cls("entertainment_video_games")
    
    @schemas.classproperty
    def ENTERTAINMENT_OTHER_ENTERTAINMENT(cls):
        return cls("entertainment_other_entertainment")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR(cls):
        return cls("food_and_drink_beer_wine_and_liquor")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_COFFEE(cls):
        return cls("food_and_drink_coffee")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_FAST_FOOD(cls):
        return cls("food_and_drink_fast_food")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_GROCERIES(cls):
        return cls("food_and_drink_groceries")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_RESTAURANT(cls):
        return cls("food_and_drink_restaurant")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_VENDING_MACHINES(cls):
        return cls("food_and_drink_vending_machines")
    
    @schemas.classproperty
    def FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK(cls):
        return cls("food_and_drink_other_food_and_drink")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS(cls):
        return cls("general_merchandise_bookstores_and_newsstands")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES(cls):
        return cls("general_merchandise_clothing_and_accessories")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_CONVENIENCE_STORES(cls):
        return cls("general_merchandise_convenience_stores")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_DEPARTMENT_STORES(cls):
        return cls("general_merchandise_department_stores")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_DISCOUNT_STORES(cls):
        return cls("general_merchandise_discount_stores")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_ELECTRONICS(cls):
        return cls("general_merchandise_electronics")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES(cls):
        return cls("general_merchandise_gifts_and_novelties")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_OFFICE_SUPPLIES(cls):
        return cls("general_merchandise_office_supplies")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_ONLINE_MARKETPLACES(cls):
        return cls("general_merchandise_online_marketplaces")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_PET_SUPPLIES(cls):
        return cls("general_merchandise_pet_supplies")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_SPORTING_GOODS(cls):
        return cls("general_merchandise_sporting_goods")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_SUPERSTORES(cls):
        return cls("general_merchandise_superstores")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_TOBACCO_AND_VAPE(cls):
        return cls("general_merchandise_tobacco_and_vape")
    
    @schemas.classproperty
    def GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE(cls):
        return cls("general_merchandise_other_general_merchandise")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT_FURNITURE(cls):
        return cls("home_improvement_furniture")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT_HARDWARE(cls):
        return cls("home_improvement_hardware")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE(cls):
        return cls("home_improvement_repair_and_maintenance")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT_SECURITY(cls):
        return cls("home_improvement_security")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT(cls):
        return cls("home_improvement_other_home_improvement")
    
    @schemas.classproperty
    def MEDICAL_DENTAL_CARE(cls):
        return cls("medical_dental_care")
    
    @schemas.classproperty
    def MEDICAL_EYE_CARE(cls):
        return cls("medical_eye_care")
    
    @schemas.classproperty
    def MEDICAL_NURSING_CARE(cls):
        return cls("medical_nursing_care")
    
    @schemas.classproperty
    def MEDICAL_PHARMACIES_AND_SUPPLEMENTS(cls):
        return cls("medical_pharmacies_and_supplements")
    
    @schemas.classproperty
    def MEDICAL_PRIMARY_CARE(cls):
        return cls("medical_primary_care")
    
    @schemas.classproperty
    def MEDICAL_VETERINARY_SERVICES(cls):
        return cls("medical_veterinary_services")
    
    @schemas.classproperty
    def MEDICAL_OTHER_MEDICAL(cls):
        return cls("medical_other_medical")
    
    @schemas.classproperty
    def PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS(cls):
        return cls("personal_care_gyms_and_fitness_centers")
    
    @schemas.classproperty
    def PERSONAL_CARE_HAIR_AND_BEAUTY(cls):
        return cls("personal_care_hair_and_beauty")
    
    @schemas.classproperty
    def PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING(cls):
        return cls("personal_care_laundry_and_dry_cleaning")
    
    @schemas.classproperty
    def PERSONAL_CARE_OTHER_PERSONAL_CARE(cls):
        return cls("personal_care_other_personal_care")
    
    @schemas.classproperty
    def GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING(cls):
        return cls("general_services_accounting_and_financial_planning")
    
    @schemas.classproperty
    def GENERAL_SERVICES_AUTOMOTIVE(cls):
        return cls("general_services_automotive")
    
    @schemas.classproperty
    def GENERAL_SERVICES_CHILDCARE(cls):
        return cls("general_services_childcare")
    
    @schemas.classproperty
    def GENERAL_SERVICES_CONSULTING_AND_LEGAL(cls):
        return cls("general_services_consulting_and_legal")
    
    @schemas.classproperty
    def GENERAL_SERVICES_EDUCATION(cls):
        return cls("general_services_education")
    
    @schemas.classproperty
    def GENERAL_SERVICES_INSURANCE(cls):
        return cls("general_services_insurance")
    
    @schemas.classproperty
    def GENERAL_SERVICES_POSTAGE_AND_SHIPPING(cls):
        return cls("general_services_postage_and_shipping")
    
    @schemas.classproperty
    def GENERAL_SERVICES_STORAGE(cls):
        return cls("general_services_storage")
    
    @schemas.classproperty
    def GENERAL_SERVICES_OTHER_GENERAL_SERVICES(cls):
        return cls("general_services_other_general_services")
    
    @schemas.classproperty
    def GOVERNMENT_AND_NON_PROFIT_DONATIONS(cls):
        return cls("government_and_non_profit_donations")
    
    @schemas.classproperty
    def GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES(cls):
        return cls("government_and_non_profit_government_departments_and_agencies")
    
    @schemas.classproperty
    def GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT(cls):
        return cls("government_and_non_profit_tax_payment")
    
    @schemas.classproperty
    def GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT(cls):
        return cls("government_and_non_profit_other_government_and_non_profit")
    
    @schemas.classproperty
    def TRANSPORTATION_BIKES_AND_SCOOTERS(cls):
        return cls("transportation_bikes_and_scooters")
    
    @schemas.classproperty
    def TRANSPORTATION_GAS(cls):
        return cls("transportation_gas")
    
    @schemas.classproperty
    def TRANSPORTATION_PARKING(cls):
        return cls("transportation_parking")
    
    @schemas.classproperty
    def TRANSPORTATION_PUBLIC_TRANSIT(cls):
        return cls("transportation_public_transit")
    
    @schemas.classproperty
    def TRANSPORTATION_TAXIS_AND_RIDE_SHARES(cls):
        return cls("transportation_taxis_and_ride_shares")
    
    @schemas.classproperty
    def TRANSPORTATION_TOLLS(cls):
        return cls("transportation_tolls")
    
    @schemas.classproperty
    def TRANSPORTATION_OTHER_TRANSPORTATION(cls):
        return cls("transportation_other_transportation")
    
    @schemas.classproperty
    def TRAVEL_FLIGHTS(cls):
        return cls("travel_flights")
    
    @schemas.classproperty
    def TRAVEL_LODGING(cls):
        return cls("travel_lodging")
    
    @schemas.classproperty
    def TRAVEL_RENTAL_CARS(cls):
        return cls("travel_rental_cars")
    
    @schemas.classproperty
    def TRAVEL_OTHER_TRAVEL(cls):
        return cls("travel_other_travel")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_GAS_AND_ELECTRICITY(cls):
        return cls("rent_and_utilities_gas_and_electricity")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_INTERNET_AND_CABLE(cls):
        return cls("rent_and_utilities_internet_and_cable")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_RENT(cls):
        return cls("rent_and_utilities_rent")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT(cls):
        return cls("rent_and_utilities_sewage_and_waste_management")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_TELEPHONE(cls):
        return cls("rent_and_utilities_telephone")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_WATER(cls):
        return cls("rent_and_utilities_water")
    
    @schemas.classproperty
    def RENT_AND_UTILITIES_OTHER_UTILITIES(cls):
        return cls("rent_and_utilities_other_utilities")
